#!/bin/bash

rm telarray_rand.conf.used > /dev/null 2>&1
rm -r simtools-output  > /dev/null 2>&1
rm data/test-plots/*  > /dev/null 2>&1
rm data/test-output/*  > /dev/null 2>&1
rm *pdf  > /dev/null 2>&1
