# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:

    VERSION_TUPLE = tuple[int | str, ...]
else:
    VERSION_TUPLE = object

version: str
__version__: str
__version_tuple__: VERSION_TUPLE
version_tuple: VERSION_TUPLE

__version__ = version = "0.8.2.dev14+gf0e6deb55.d20241129"
__version_tuple__ = version_tuple = (0, 8, 2, "dev14", "gf0e6deb55.d20241129")
