FROM ghcr.io/gammasim/simtools-corsika_sim_telarray
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    python3-venv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN git clone -b main https://github.com/gammasim/simtools.git --depth 1
RUN cd /workdir/ && \
    python3 -m venv env && \
    source env/bin/activate && \
    cd /workdir/simtools/ && \
    pip install --no-cache-dir .

ENV SIMTEL_PATH="/workdir/sim_telarray/"
ENV PATH="/workdir/env/bin/:$PATH"
SHELL ["/bin/bash", "-c"]

WORKDIR /workdir
