FROM almalinux:9.5 AS build_image
WORKDIR /workdir/sim_telarray
ENV DEBIAN_FRONTEND=noninteractive
ENV GCC_PATH="/usr/bin/"
ARG BUILD_OPT="prod6-sc"
ARG HADRONIC_MODEL="qgs2"
ARG AVX_FLAG="avx2"
ARG CORSIKA_VERSION="77550"
ARG BERNLOHR_VERSION="1.68"

RUN yum update -y && yum install -y \
    autoconf \
    automake \
    csh \
    perl \
    which \
    gcc-fortran \
    gfortran \
    gsl-devel \
    libgfortran \
    patch && \
    yum clean all

ADD corsika_simtelarray.tar.gz .
ADD corsikaOptPatch.tar.gz ./corsika-$CORSIKA_VERSION
RUN tar -zxvf corsika-$CORSIKA_VERSION.tar.gz && \
    tar -zxvf bernlohr-$BERNLOHR_VERSION.tar.gz -C corsika-$CORSIKA_VERSION/bernlohr && \
    rm -f examples-with-data.tar.gz && \
    rm -f sim_telarray_config.tar.gz

# build (optimized) corsika
RUN cd corsika-$CORSIKA_VERSION && \
    if [ "$AVX_FLAG" != "noopt" ]; then \
        ./corsika_opt_patching.sh && autoreconf; \
    fi  && \
    ../corsika_build_script $HADRONIC_MODEL generic cerenkopt vlibm

RUN make -C corsika-$CORSIKA_VERSION clean && rm -f */*.a lib/*/*.a && \
    if [ "${AVX_FLAG}" = "avx512f" ]; then \
        avx_512_FLAG="-ffp-contract=off"; \
    else \
        avx_512_FLAG=""; \
    fi; \
    echo "AVX_FLAG=${AVX_FLAG}"; \
    make -C corsika-$CORSIKA_VERSION \
        CC="${GCC_PATH}/gcc -static" \
        CXX="${GCC_PATH}/g++ -static" \
        CPP="${GCC_PATH}/gcc -static -E" \
        F77="${GCC_PATH}/gfortran -L/lib64/" \
        CFLAGS="-DCERENKOPT -DVLIBM -std=c99 -O3 ${AVX_FLAG:+-m$AVX_FLAG} ${avx_512_FLAG} -DVECTOR_SIZE=8 -DVECTOR_LENGTH=8" \
        CXXFLAGS="-DCERENKOPT -DVLIBM -std=c99 -O3 ${AVX_FLAG:+-m$AVX_FLAG} ${avx_512_FLAG} -DVECTOR_SIZE=8 -DVECTOR_LENGTH=8" \
        FFLAGS="-ffixed-line-length-132 -fno-automatic -frecord-marker=4 -std=legacy -DCERENKOPT -DVLIBM -std=c99 -O3 ${AVX_FLAG:+-m$AVX_FLAG} ${avx_512_FLAG} -DVECTOR_SIZE=8 -DVECTOR_LENGTH=8" \
        install

# Rename executable to 'corsika'
RUN mv -f corsika-$CORSIKA_VERSION/run/corsika$CORSIKA_VERSIONLinux_*ceropt corsika-$CORSIKA_VERSION/run/corsika

RUN export NO_CORSIKA=1 && ./build_all $BUILD_OPT $HADRONIC_MODEL gsl

# cleanup
# corsika source code is removed to follow
# the corsika non-distribution policy.
RUN mv ./corsika-77*/run corsika-run && \
    rm -rf ./corsika-7[0-9]* && \
    find . -name "*.tar.gz" -exec rm -f {} \;

FROM almalinux:9.5-minimal
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive
COPY --from=build_image /workdir/sim_telarray/ /workdir/sim_telarray/

RUN microdnf update -y && microdnf install -y \
    bc \
    zstd \
    gsl-devel \
    gcc-fortran \
    libgfortran \
    procps && \
    microdnf clean all

# create a symbolic link to the corsika executable
RUN cprog=$(/bin/ls /workdir/sim_telarray/corsika-run/corsika*$(uname)_* 2>/dev/null | tail -1) && \
    ln -sf $cprog /workdir/sim_telarray/corsika-run/corsika

ENV SIMTEL_PATH="/workdir/sim_telarray/"

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/
