# syntax=docker/dockerfile:1.4
# Dockerfile for base CORSIKA7
#
# Contains CORSIKA (possibly optimized; with and without curved atmosphere)
#

# Shared build arguments
ARG CORSIKA_VERSION="78010"
ARG CORSIKA_OPT_PATCH_VERSION="v1.1.0"
ARG HADRONIC_MODEL="qgs3"
ARG HADRONIC_MODEL_LE="urqmd"
ARG AVX_FLAG="avx2"
ARG BERNLOHR_VERSION="1.70"
ARG AUTOCONF_VERSION="2.71"

# hadolint global ignore=DL3013,DL3033,DL3041,SC1091
# - DL3013, DL3033: ignore warnings about installing non-specific versions with microdnf or yum)
# - SC1091: ignore warning about not being able to source the bashrc

# -----------------------------------------------------------------------------
# STAGE 1: source_preparation
# Centralizes all source code preparation and extraction.
# -----------------------------------------------------------------------------
FROM almalinux:9.5 AS source_preparation
ARG CORSIKA_VERSION
ARG CORSIKA_REPO="gitlab.iap.kit.edu/AirShowerPhysics/corsika-legacy/corsika7.git"
ARG CORSIKA_OPT_PATCH_VERSION
ARG CORSIKA_OPT_PATCH_REPO="gitlab.cta-observatory.org/cta-computing/dpps/simpipe/simulation_software/corsika-opt-patches.git"
ARG CORSIKA_CONFIG_REPO="https://gitlab.cta-observatory.org/cta-computing/dpps/simpipe/simulation_software/corsika7-config.git"
ARG BERNLOHR_VERSION
ARG AUTOCONF_VERSION
ARG HADRONIC_MODEL

RUN yum update -y --setopt=tsflags=nodocs && \
    yum install -y git tar gzip && \
    yum clean all

WORKDIR /src
ENV CORSIKA_DIR="corsika-${CORSIKA_VERSION}"

# Clone CORSIKA configuration files from CTAO gitlab
RUN git config --global advice.detachedHead false && \
    git clone --depth 1 --branch "${CORSIKA_VERSION}" "${CORSIKA_CONFIG_REPO}" && \
    cp -v corsika7-config/config/${CORSIKA_VERSION}/*.h . && \
    rm -rf corsika7-config

# TODO - clone CORSIKA from KIT gitlab
# TODO - address how to use newest IACT version (part of sim_telarray; could also clone from gitlab)
RUN --mount=type=secret,id=corsika7_token \
    git config --global advice.detachedHead false && \
    git clone --depth 1 --branch "v7.8010" "https://oauth2:$(cat /run/secrets/corsika7_token)@${CORSIKA_REPO}"  && \
    ls -la
