From ubuntu:23.04 as build_image
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    bash \
    build-essential \
    bzip2 \
    csh \
    gfortran \
    gcc \
    g++ \
    libgsl-dev \
    make \
    unzip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# corsika and sim_telarray
# (corsika source code is removed to follow
# the corsika non-distribution policy)
RUN mkdir sim_telarray
COPY corsika7.7_simtelarray.tar.gz sim_telarray
RUN cd sim_telarray && \
    tar -xvf corsika7.7_simtelarray.tar.gz && \
    ./build_all prod5 qgs2 gsl

RUN find sim_telarray/ -name "*.tar.gz" -exec rm -f {} \;
RUN rm -f sim_telarray/corsika-run && \
    mv sim_telarray/corsika-77*/run sim_telarray/corsika-run && \
    rm -rf sim_telarray/corsika-77*

From ubuntu:23.04
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive
COPY --from=build_image /workdir/sim_telarray/ /workdir/sim_telarray/

RUN apt-get update && apt-get install -y \
    bc \
    bzip2 \
    gfortran \
    libgsl-dev \
    unzip \
    zstd && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

ENV SIMTEL_PATH="/workdir/sim_telarray/"

SHELL ["/bin/bash", "-c"]
WORKDIR /workdir/
