# syntax=docker/dockerfile:1.4
# Dockerfile for base CORSIKA7
#
# Contains CORSIKA (possibly optimized; with and without curved atmosphere)
#

# Shared build arguments
ARG CORSIKA_VERSION="78010"
ARG CORSIKA_OPT_PATCH_VERSION="v1.1.0"
ARG HADRONIC_MODEL="qgs3"
ARG HADRONIC_MODEL_LE="urqmd"
ARG AVX_FLAG="avx2"
ARG BERNLOHR_VERSION="1.70"
ARG AUTOCONF_VERSION="2.71"

# hadolint global ignore=DL3013,DL3033,DL3041,SC1091
# - DL3013, DL3033: ignore warnings about installing non-specific versions with microdnf or yum)
# - SC1091: ignore warning about not being able to source the bashrc

# -----------------------------------------------------------------------------
# STAGE 1: source_preparation
# Centralizes all source code preparation and extraction.
# -----------------------------------------------------------------------------
FROM almalinux:9.5 AS source_preparation
ARG CORSIKA_VERSION
ARG CORSIKA_REPO="gitlab.iap.kit.edu/AirShowerPhysics/corsika-legacy/corsika7.git"
ARG CORSIKA_OPT_PATCH_VERSION
ARG CORSIKA_OPT_PATCH_REPO="gitlab.cta-observatory.org/cta-computing/dpps/simpipe/simulation_software/corsika-opt-patches.git"
ARG CORSIKA_CONFIG_REPO="gitlab.cta-observatory.org/cta-computing/dpps/simpipe/simulation_software/corsika7-config.git"
ARG BERNLOHR_VERSION
ARG AUTOCONF_VERSION
ARG HADRONIC_MODEL

RUN yum update -y --setopt=tsflags=nodocs && \
    yum install -y git && \
    yum clean all

WORKDIR /src
ENV CORSIKA_DIR="corsika7"

# Clone CORSIKA configuration files from CTAO gitlab
RUN git config --global advice.detachedHead false && \
    git clone --depth 1 --branch "${CORSIKA_VERSION}" "http://${CORSIKA_CONFIG_REPO}" && \
    cp -v corsika7-config/config/${CORSIKA_VERSION}/*.h . && \
    rm -rf corsika7-config

# Clone CORSIKA from KIT gitlab (note change in version tag format: e.g., v7.8010)
RUN --mount=type=secret,id=corsika7_token \
    CORSIKA_CONFIG_TAG="v${CORSIKA_VERSION:0:1}.${CORSIKA_VERSION:1}" && \
    git config --global advice.detachedHead false && \
    git clone --depth 1 --branch "${CORSIKA_CONFIG_TAG}" "https://oauth2:$(cat /run/secrets/corsika7_token)@${CORSIKA_REPO}"

# Clone CORSIKA optimization patches from CTAO gitlab
RUN --mount=type=secret,id=opt_patches_token \
    git config --global advice.detachedHead false && \
    git clone --depth 1 --branch "${CORSIKA_OPT_PATCH_VERSION}" "https://${CORSIKA_OPT_PATCH_REPO}" && \
    cp -rL corsika-opt-patches/build_opt/corsikaOptPatch-$CORSIKA_VERSION/* ${CORSIKA_DIR}/ && \
    rm -rf corsika-opt-patches

# -----------------------------------------------------------------------------
# STAGE 2: build_image
# Installs necessary build dependencies and performs the compilation.
# -----------------------------------------------------------------------------
FROM almalinux:9.5 AS build_image
ARG HADRONIC_MODEL
ARG HADRONIC_MODEL_LE
ARG AVX_FLAG
ARG CORSIKA_VERSION
ARG BERNLOHR_VERSION
ARG CORSIKA_OPT_PATCH_VERSION
ARG AUTOCONF_VERSION
ARG C_SPECIFIC_FLAGS="-std=c99"
ARG FORTRAN_SPECIFIC_FLAGS="-ffixed-line-length-132 -fno-automatic -frecord-marker=4 -std=legacy"

ENV GCC_PATH="/usr/bin/"
ENV CORSIKA_DIR="corsika7"

RUN yum update -y --setopt=tsflags=nodocs && \
    yum install -y \
    autoconf271 automake diffutils csh gcc gcc-c++ gcc-fortran libtool m4 patch && \
    yum clean all

WORKDIR /workdir/simulation_software
COPY --from=source_preparation /src .
WORKDIR /workdir/simulation_software/${CORSIKA_DIR}

# Apply patches for non-optimized / optimized CORSIKA
RUN if [ "$CORSIKA_VERSION" = "77550" ]; then \
        patch -b -p0 "src/corsika.F" < "../corsika-77550.patch"; \
    fi && \
    if [ "$AVX_FLAG" != "no_opt" ]; then \
        "./corsika_opt_patching.sh" && \
        autoreconf; \
    fi

# Build non-optimized / optimized CORSIKA
RUN for variant in curved flat; do \
        ./coconut -d && rm -f ./*/*.a lib/*/*.a included/* && \
        # CTAO specific CORSIKA configuration
        cp -v ../config_${CORSIKA_VERSION}_${HADRONIC_MODEL_LE}_${HADRONIC_MODEL}_${variant}.h include/config.h; \
        # compilation flags (with or without optimization)
        AVX_EXTRA_FLAG=$([ "$AVX_FLAG" = "avx512f" ] && echo "-ffp-contract=off" || echo "") && \
        if [ "$AVX_FLAG" = "no_opt" ] || [ "$variant" = "curved" ]; then \
            BASE_FLAGS="-g -O3"; \
        else \
            BASE_FLAGS="-g -DCERENKOPT -DVLIBM -O3 ${AVX_FLAG:+-m$AVX_FLAG} ${AVX_EXTRA_FLAG} -DVECTOR_SIZE=8 -DVECTOR_LENGTH=8"; \
            echo "#define __CERENKOPT__ 1" >> include/config.h; \
            echo "#define __VLIBM__ 1" >> include/config.h; \
        fi && \
        CFLAGS="${BASE_FLAGS} ${C_SPECIFIC_FLAGS}" \
        CXXFLAGS="${BASE_FLAGS} ${C_SPECIFIC_FLAGS}" \
        FFLAGS="${BASE_FLAGS} ${FORTRAN_SPECIFIC_FLAGS}" \
        # compile using the coconut script
        CORSIKA_USER_COMP=1 ./coconut --expert --without-root --without-COASTUSERLIB --without-conex < /dev/null; \
        # move built corsika binary and compile file to a separate directory
        CORSIKA_RUN_DIR="/workdir/corsika-run" && \
        mkdir -p ${CORSIKA_RUN_DIR} && \
        mv -v -f "./run/corsika${CORSIKA_VERSION}Linux_"* "${CORSIKA_RUN_DIR}/corsika-$variant" && \
        cp -r -v "./run/"* ${CORSIKA_RUN_DIR}/; \
    done

# -----------------------------------------------------------------------------
# STAGE 3: Final Image (Runtime)
# -----------------------------------------------------------------------------
FROM almalinux:9.5-minimal
WORKDIR /workdir/simulation_software
COPY --from=build_image /workdir/corsika-run /workdir/simulation_software/corsika

RUN microdnf update -y && microdnf install -y \
    gcc-fortran && \
    microdnf clean all

WORKDIR /workdir/simulation_software/corsika
