From ghcr.io/gammasim/simtools-simtelarray
WORKDIR /workdir
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    python3-pip \
    wget && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN wget --quiet https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    rm -f get-pip.py

RUN git clone https://github.com/gammasim/simtools.git

ENV SIMTEL_PATH="/workdir/sim_telarray/"
SHELL ["/bin/bash", "-c"]

RUN cd /workdir/simtools && \
    pip install --no-cache-dir .

WORKDIR /workdir/
