''' Parameters of telescope model. '''

__all__ = ['MODEL_PARS']

MODEL_PARS = {
    'focal_length': {'type': float, 'names': []},
    'fadc_mhz': {'type': float, 'names': ['fadc_MHz']},
    'quantum_efficiency': {'type': str, 'names': ['quantum_eff']},
    'telescope_transmission': {'type': str, 'names': ['telescope_trans']},
    'camera_transmission': {'type': str, 'names': ['camera_trans']},
    'trigger_telescopes': {'type': int, 'names': []},
    'iobuf_maximum': {'type': int, 'names': ['iobuf_max']},
    'iobuf_output_maximum': {'type': int, 'names': ['iobuf_output_max']},
    'only_triggered_telescopes': {'type': int, 'names': []},
    'store_photoelectrons': {'type': int, 'names': []},
    'sum_after_peak': {'type': int, 'names': []},
    'sum_before_peak': {'type': int, 'names': []},
    'trigger_pixels': {'type': int, 'names': ['trigger_pixel']},
    'pixel_cells': {'type': int, 'names': []},
    'pixels_parallel': {'type': int, 'names': []},
    # 'pm_transit_time': {'type': int, 'names': []},
    'pulse_analysis': {'type': int, 'names': []},
    'num_gains': {'type': int, 'names': []},
    'output_format': {'type': int, 'names': []},
    'peak_sensing': {'type': int, 'names': []},
    'fadc_sum_offset': {'type': int, 'names': []},
    'flatfielding': {'type': int, 'names': []},
    'mirror_class': {'type': int, 'names': []},
    'fadc_max_signal': {'type': int, 'names': []},
    'fadc_max_sum': {'type': int, 'names': []},
    'fadc_sum_bins': {'type': int, 'names': []},
    'fadc_bins': {'type': int, 'names': []},
    'fadc_lg_max_signal': {'type': int, 'names': []},
    'fadc_lg_max_sum': {'type': int, 'names': []},
    'disc_bins': {'type': int, 'names': []},
    'disc_start': {'type': int, 'names': []},
    'fadc_ac_coupled': {'type': int, 'names': []},
    'camera_pixels': {'type': int, 'names': ['camera_pixel']},
    'disc_ac_coupled': {'type': int, 'names': []},
    'camera_body_shape': {'type': int, 'names': []},
    'min_photoelectrons': {'type': int, 'names': []},
    'parabolic_dish': {'type': int, 'names': []}
}
