---
name: 'Setup Model Database'
description: 'Extract simulation model variables, determine branch, and upload to MongoDB'
inputs:
  simulation_model_branch:
    description: 'Override simulation model branch'
    required: false
  skip_upload:
    description: 'Skip database upload (e.g., for scheduled runs)'
    required: false
    default: 'false'
outputs:
  simulation_model:
    description: 'Simulation model name'
    value: ${{ steps.extract.outputs.model }}
  simulation_model_version:
    description: 'Simulation model version'
    value: ${{ steps.extract.outputs.version }}
  simulation_model_branch:
    description: 'Simulation model branch'
    value: ${{ steps.determine.outputs.branch }}
runs:
  using: 'composite'
  steps:
    - name: Extract simulation model variables
      id: extract
      shell: bash
      run: |
        VERSION=$(grep 'SIMTOOLS_DB_SIMULATION_MODEL_VERSION=' .env_template | cut -d '=' -f2- | tr -d '"')
        MODEL=$(grep 'SIMTOOLS_DB_SIMULATION_MODEL=' .env_template | cut -d '=' -f2- | tr -d '"')
        MODEL="${MODEL//\'/}"
        echo "model=$MODEL" >> "$GITHUB_OUTPUT"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "SIMTOOLS_DB_SIMULATION_MODEL=$MODEL" >> "$GITHUB_ENV"
        echo "SIMTOOLS_DB_SIMULATION_MODEL_VERSION=$VERSION" >> "$GITHUB_ENV"
        echo "Simulation model set to: $MODEL version $VERSION"

    - name: Determine simulation model branch
      id: determine
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.simulation_model_branch }}
      run: |
        if [ -n "$INPUT_BRANCH" ]; then
          BRANCH="$INPUT_BRANCH"
        else
          BRANCH="main"
        fi
        CURRENT_REF="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
        if [[ "$CURRENT_REF" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]*$ ]]; then
          echo "Detected RC version branch: $CURRENT_REF - setting branch to ${{ steps.extract.outputs.version }}"
          BRANCH="${{ steps.extract.outputs.version }}"
        fi
        echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"
        echo "SIMTOOLS_DB_SIMULATION_MODEL_BRANCH=$BRANCH" >> "$GITHUB_ENV"

    - name: Print DB connection variables
      shell: bash
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "DB Server: $SIMTOOLS_DB_SERVER"
        echo "DB API User: $SIMTOOLS_DB_API_USER"
        echo "DB API Port: $SIMTOOLS_DB_API_PORT"
        echo "DB Simulation Model: ${{ steps.extract.outputs.model }}"
        echo "DB Simulation Model Version: ${{ steps.extract.outputs.version }}"
        echo "DB Simulation Model Branch: ${{ steps.determine.outputs.branch }}"

    - name: Install simtools
      shell: bash
      run: |
        pip install -e .

    - name: Upload to MongoDB
      if: inputs.skip_upload != 'true'
      shell: bash
      run: |
        simtools-db-upload-model-repository \
          --db_simulation_model ${{ steps.extract.outputs.model }} \
          --db_simulation_model_version ${{ steps.extract.outputs.version }} \
          --branch "${{ steps.determine.outputs.branch }}"
