---
name: 'Setup Model Database'
description: 'Extract simulation model variables, determine branch, and upload to MongoDB'
inputs:
  simulation_model_branch:
    description: 'Override simulation model branch'
    required: false
  skip_upload:
    description: 'Skip database upload (e.g., for scheduled runs)'
    required: false
    default: 'false'
outputs:
  simulation_model:
    description: 'Simulation model name'
    value: ${{ steps.setup.outputs.model }}
  simulation_model_version:
    description: 'Simulation model version'
    value: ${{ steps.setup.outputs.version }}
  simulation_model_branch:
    description: 'Simulation model branch'
    value: ${{ steps.setup.outputs.branch }}

runs:
  using: composite
  steps:

    - name: Extract model variables and determine branch
      id: setup
      shell: bash
      env:
        INPUT_BRANCH: ${{ inputs.simulation_model_branch }}
      run: |
        set -euo pipefail
        set -a
        source .env_template
        set +a

        MODEL="${SIMTOOLS_DB_SIMULATION_MODEL//\'}"
        VERSION="$SIMTOOLS_DB_SIMULATION_MODEL_VERSION"

        # Default branch
        BRANCH="${INPUT_BRANCH:-main}"

        CURRENT_REF="${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"

        # RC tags use released model version
        if [[ "$CURRENT_REF" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-rc[0-9]*$ ]]; then
          BRANCH="$VERSION"
        fi

        echo "model=$MODEL"   >> "$GITHUB_OUTPUT"
        echo "version=$VERSION" >> "$GITHUB_OUTPUT"
        echo "branch=$BRANCH" >> "$GITHUB_OUTPUT"

        echo "Simulation model: $MODEL"
        echo "Version: $VERSION"
        echo "Branch: $BRANCH"

    - name: Install simtools
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .

    - name: Upload to MongoDB
      if: inputs.skip_upload != 'true'
      shell: bash
      run: |
        simtools-db-upload-model-repository \
          --db_simulation_model "${{ steps.setup.outputs.model }}" \
          --db_simulation_model_version "${{ steps.setup.outputs.version }}" \
          --branch "${{ steps.setup.outputs.branch }}"
