---
$schema: http://json-schema.org/draft-06/schema#
$ref: '#/definitions/SimtoolsIntegrationTestConfiguration'
title: SimPipe integration test configuration metaschema
description: YAML representation of integration test configuration metaschema
version: 0.2.0
name: integration_tests_config.metaschema
type: object
additionalProperties: false


definitions:
  SimtoolsIntegrationTestConfiguration:
    type: object
    additionalProperties: false
    properties:
      CTA_SIMPIPE:
        "$ref": "#/definitions/CTASIMPIPE"
    required:
      - CTA_SIMPIPE
    title: ""
  CTASIMPIPE:
    type: object
    additionalProperties: false
    properties:
      APPLICATION:
        type: string
        description: "Name of simtools application"
      TEST_NAME:
        type: string
        description: "Test name. Should be unique for this application."
      MODEL_VERSION_USE_CURRENT:
        type: boolean
        description: |
          "Skip test if model version is changed via command line.
          Important e.g., for cases where DB model is incomplete for some
          model versions."
      CONFIGURATION:
        "$ref": "#/definitions/Configuration"
      INTEGRATION_TESTS:
        type: array
        items:
          "$ref": "#/definitions/IntegrationTest"
    required:
      - APPLICATION
      - CONFIGURATION
      - TEST_NAME
    title: CTASimpipe
  Configuration:
    description: "Command line configuration of simtools application."
    type: object
    additionalProperties: true
    title: Configuration
  IntegrationTest:
    description: "List of integration tests."
    type: object
    additionalProperties: false
    properties:
      OUTPUT_FILE:
        description: |
          "Path of output file tested to be generated by integration test."
        type: string
      TEST_OUTPUT_FILES:
        type: array
        items:
          type: object
          properties:
            PATH_DESCRIPTOR:
              type: string
            FILE:
              type: string
            EXPECTED_OUTPUT:
              description: |
                "Expected output of integration test."
              type: object
          required: ["PATH_DESCRIPTOR", "FILE"]
      FILE_TYPE:
        description: |
          "Expected file type of output file generated by integration test."
        type: string
      REFERENCE_OUTPUT_FILE:
        description: |
          "Reference file used for comparison."
        type: string
      TEST_SIMTEL_CFG_FILES:
        description: |
          "Reference file used for comparison of sim_telarray configuration files."
        type: object
        additionalProperties: false
        patternProperties:
          "^[0-9]+\\.[0-9]+\\.[0-9]+$":  # Semantic versioning pattern (e.g., "5.0.0", "6.0.0")
            type: string
            description: Path to the configuration file for the given version.
        minProperties: 1
      TOLERANCE:
        description: "Allowed tolerance for floating point comparison."
        type: number
      TEST_COLUMNS:
        description: "List of columns to be compared, each with optional cut conditions."
        type: array
        items:
          type: object
          properties:
            TEST_COLUMN_NAME:
              description: "Name of the column to compare."
              type: string
            CUT_COLUMN_NAME:
              description: "Name of the column for applying the cut."
              type: string
            CUT_CONDITION:
              description: "Condition to apply to the cut column."
              type: string
    title: IntegrationTest
