---
$schema: http://json-schema.org/draft-06/schema#
$ref: '#/definitions/ProductionModelTable'
title: SimPipe DB Production Model Metaschema
description: |
  YAML representation of DB production model metaschema
  (based on simulation model DB).
schema_version: 0.1.0
schema_name: production_table.metaschema
type: object
additionalProperties: false

definitions:
  ProductionModelTable:
    additionalProperties: false
    properties:
      production_table_name:
        type: string
        description: Name of the production table.
      model_version:
        $ref: 'common_definitions.schema.yml#/$defs/semantic_version_pattern'
      parameters:
        type: object
        description: Model parameters.
        additionalProperties:
          type: object
          description: Model parameter.
          additionalProperties:
            $ref: 'common_definitions.schema.yml#/$defs/semantic_version_pattern'
        propertyNames:
          $ref: 'common_definitions.schema.yml#/$defs/telescope_name_pattern'
      design_model:
        type: object
        description: Design models.
        additionalProperties:
          type: string
          description: Design model of a telescope
      deprecated_parameters:
        type: array
        description: List of deprecated parameters.
        items:
          type: string
    required:
      - production_table_name
      - model_version
      - parameters
