#!/usr/bin/python3

r"""
Generate scan grids for NSB (gamma) and proton telescope trigger bias curves.

This application always prepares both curves:

- NSB curve with gamma primary
- Proton curve with proton primary

For each curve, the application creates a backend-neutral production grid and
parameter-scan grid:

- ``base_grid.ecsv``
- ``scan_config.yaml``
- ``scan_grid.ecsv``

No backend-specific submission files are generated by this application. The
resulting scan grids can be consumed by a backend-specific submission generator,
for example ``simtools-simulate-prod-htcondor-generator``.

Trigger-threshold scan values have telescope-type defaults and can be overridden
with ``threshold_values``. Energy ranges, the model-parameter version, and NSB
scaling are configurable in the same way.

The telescope is resolved from ``array_layout_name`` using the site model. This
application currently supports only single-telescope layouts. The threshold
parameter is chosen automatically from the telescope type:

- LST: ``asum_threshold``
- MST: ``dsum_threshold``

Default energy ranges are:

- NSB gamma curve: ``20 MeV 25 MeV``
- Proton curve: ``2 GeV 2000 GeV``

Overwrite model-parameter files are generated dynamically from scratch through
``simtools-generate-parameter-scan-grid``. No external overwrite templates are
needed.

Command line arguments
----------------------
site (str, required)
    Observation site (e.g., North, South).
model_version (str, required)
    Simulation model version.
array_layout_name (str, required)
    Single-telescope array layout name for simulations.
simulation_software (str)
    Simulation software (default: corsika_sim_telarray).
azimuth_angle (float, required)
    Azimuth angle in degrees.
zenith_angle (float, required)
    Zenith angle in degrees.
showers_per_run (int, required)
    Number of showers per run.
core_scatter (str, required)
    Core scatter (e.g., "20 1900 m").
view_cone (str, required)
    View cone (e.g., "0 deg 5 deg").
number_of_runs (int, required)
    Number of runs.
corsika_le_interaction (str)
    CORSIKA low-energy interaction model (default: urqmd).
corsika_he_interaction (str)
    CORSIKA high-energy interaction model (default: epos).
threshold_values (float, optional)
    Trigger-threshold scan values. Telescope-type defaults are used when omitted.
nsb_energy_range (str)
    NSB gamma energy range (default: "20 MeV 25 MeV").
proton_energy_range (str)
    Proton energy range (default: "2 GeV 2000 GeV").
model_parameter_version (str)
    Version assigned to generated model-parameter overwrites (default: 2.0.0).
nsb_scaling_factor (float)
    NSB scaling used by both curves (default: 2).
output_path (Path)
    Root output directory; nsb/ and proton/ sub-dirs are created inside it
    (provided by framework, default: ./simtools-output/).

Example
-------
.. code-block:: console

    simtools-generate-bias-curve-submissions \
        --site North \
        --model_version 7.0.0 \
        --array_layout_name LSTN-01 \
        --azimuth_angle 0.0 \
        --zenith_angle 20.0 \
        --showers_per_run 10000 \
        --core_scatter "20 1900 m" \
        --view_cone "0 deg 5 deg" \
        --number_of_runs 10 \
        --output_path ./bias_curves

Afterwards, submit files can be generated explicitly for a chosen backend, for
example:

.. code-block:: console

    simtools-simulate-prod-htcondor-generator \
        --job_grid_file ./bias_curves/nsb/scan_grid.ecsv \
        --output_path ./bias_curves/nsb/htcondor_submit \
        --apptainer_image /path/to/image.sif \
        --label nsb

"""

from simtools.application_control import build_application
from simtools.job_execution import bias_curve_submissions


def _add_arguments(parser):
    """Register application-specific command line arguments."""
    parser.add_argument(
        "--site",
        help="Observation site (e.g., North, South).",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--model_version",
        help="Simulation model version.",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--array_layout_name",
        help="Single-telescope array layout name.",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--simulation_software",
        help="Simulation software.",
        type=str,
        default="corsika_sim_telarray",
    )
    parser.add_argument(
        "--azimuth_angle",
        help="Azimuth angle in degrees.",
        type=float,
        required=True,
    )
    parser.add_argument(
        "--zenith_angle",
        help="Zenith angle in degrees.",
        type=float,
        required=True,
    )
    parser.add_argument(
        "--showers_per_run",
        help="Number of showers per run.",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--core_scatter",
        help="Core scatter, e.g. '20 1900 m'.",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--view_cone",
        help="View cone, e.g. '0 deg 5 deg'.",
        type=str,
        required=True,
    )
    parser.add_argument(
        "--number_of_runs",
        help="Number of runs.",
        type=int,
        required=True,
    )
    parser.add_argument(
        "--corsika_le_interaction",
        help="CORSIKA low-energy interaction model.",
        type=str,
        default="urqmd",
    )
    parser.add_argument(
        "--corsika_he_interaction",
        help="CORSIKA high-energy interaction model.",
        type=str,
        default="epos",
    )
    parser.add_argument(
        "--threshold_values",
        help="Trigger-threshold values; telescope-type defaults are used when omitted.",
        type=float,
        nargs="+",
    )
    parser.add_argument(
        "--nsb_energy_range",
        help="Energy range for the NSB gamma curve.",
        type=str,
        default=bias_curve_submissions.DEFAULT_NSB_ENERGY_RANGE,
    )
    parser.add_argument(
        "--proton_energy_range",
        help="Energy range for the proton curve.",
        type=str,
        default=bias_curve_submissions.DEFAULT_PROTON_ENERGY_RANGE,
    )
    parser.add_argument(
        "--model_parameter_version",
        help="Version assigned to generated model-parameter overwrites.",
        type=str,
        default=bias_curve_submissions.DEFAULT_PARAMETER_VERSION,
    )
    parser.add_argument(
        "--nsb_scaling_factor",
        help="NSB scaling factor used by both curves.",
        type=float,
        default=bias_curve_submissions.DEFAULT_NSB_SCALING_FACTOR,
    )


def main():
    """See CLI description."""
    app_context = build_application(
        application_path=__file__,
        description=__doc__,
        add_arguments_function=_add_arguments,
        initialization_kwargs={"db_config": True, "output": False},
    )
    bias_curve_submissions.generate_bias_curve_submissions(app_context.args)


if __name__ == "__main__":
    main()
