#!/usr/bin/python3

r"""
Derive CORSIKA configuration limits for energy, core distance, and viewcone radius.

This tool derives configuration limits from reduced event data generated by broad-range
simulations. It supports the derivation of the following CORSIKA configuration parameters:

- **ERANGE**: lower energy limit
- **CSCAT**: upper core distance
- **VIEWCONE**: viewcone radius

Broad-range simulations in this context are simulation sets generated with wide ranges
for these parameters.

How limits are derived
----------------------
Lower energy limit (**ERANGE**)
    Derived from the 1D triggered-energy histogram using a peak-relative threshold:

    1. Find the absolute maximum bin in the triggered-energy histogram.
    2. Compute a stable peak by averaging the maximum bin and available immediate neighbors.
    3. Define a threshold as fraction of this stable peak (``--energy_threshold_fraction``).
    4. Walk toward lower energies from the peak to the first bin below threshold.
    5. Use that bin's lower edge as the energy limit.

Upper core distance (**CSCAT**) and viewcone radius (**VIEWCONE**)
    Derived from per-axis allowed-loss settings (``--allowed_losses axis,fraction,min_events``),
    either as integrated limits or per-energy-bin
    differential limits (depending on ``--differential_loss_bins_per_decade``).
    Differential limits are preferable, as they are more robust to variations with energy.
    If every triggered event has the same angular distance, the viewcone radius is set to that
    exact value and the degenerate angular-distance-vs-energy plots are omitted.

Results are provided as a table with the following columns:

+---------------------------+-----------+--------+----------------------------------------------+
| Field                     | Data Type | Units  | Description                                  |
+===========================+===========+========+==============================================+
| production_index          | int64     |        | Production index for multi-production runs.  |
+---------------------------+-----------+--------+----------------------------------------------+
| primary_particle          | string    |        | Particle type (e.g., gamma, proton).         |
+---------------------------+-----------+--------+----------------------------------------------+
| array_layout_name         | string    |        | Array name (custom or as defined in          |
|                           |           |        | array_layouts).                              |
+---------------------------+-----------+--------+----------------------------------------------+
| zenith                    | float64   | deg    | Direction of array pointing zenith.          |
+---------------------------+-----------+--------+----------------------------------------------+
| azimuth                   | float64   | deg    | Direction of array pointing azimuth.         |
+---------------------------+-----------+--------+----------------------------------------------+
| nsb_level                 | float64   |        | Night sky background level.                  |
+---------------------------+-----------+--------+----------------------------------------------+
| lower_energy_limit        | float64   | TeV    | Derived lower energy limit (**ERANGE**).     |
+---------------------------+-----------+--------+----------------------------------------------+
| upper_radius_limit        | float64   | m      | Derived upper core distance                  |
|                           |           |        | (**CSCAT**).                                 |
+---------------------------+-----------+--------+----------------------------------------------+
| viewcone_radius           | float64   | deg    | Derived viewcone radius (**VIEWCONE**).      |
+---------------------------+-----------+--------+----------------------------------------------+
| br_energy_min             | float64   | TeV    | Energy min from broad-range simulations.     |
+---------------------------+-----------+--------+----------------------------------------------+
| br_energy_max             | float64   | TeV    | Energy max from broad-range simulations.     |
+---------------------------+-----------+--------+----------------------------------------------+
| br_core_scatter_max       | float64   | m      | Core scatter max from broad-range            |
|                           |           |        | simulations.                                 |
+---------------------------+-----------+--------+----------------------------------------------+
| br_viewcone_max           | float64   | deg    | Viewcone max from broad-range simulations.   |
+---------------------------+-----------+--------+----------------------------------------------+

The input trigger-histogram file is generated using ``simtools-write-trigger-histograms``.
It defines the sampled observational parameter space (zenith, azimuth, NSB level),
production index, and array names.

Distributions of triggered events (e.g., core distance vs energy) can be plotted to verify the
derived limits using the ``--plot_histograms`` option. Plots are organized into per-production
subdirectories derived from the input pattern names (for example ``production_production_a/``).

Command line arguments
----------------------
trigger_histogram_file (str, required)
    Precomputed trigger-histogram HDF5 file from ``simtools-write-trigger-histograms``.
array_layout_name (str, optional)
    Optional array layout name(s) to select from the trigger-histogram file.
    If omitted, limits are derived for all layouts available in the file.
allowed_losses (str, required, repeatable)
    Per-axis allowed-loss tuple in the form
    ``axis,fraction,min_events``.
    Use once per axis (core_distance, angular_distance), or use ``all``
    to set both axes and optionally override selected axes.
    Core distance and angular distance limits use these settings directly.
differential_loss_bins_per_decade (int, optional)
    Number of differential energy bins per decade for per-bin limit computation.
    Set to 0 (default) to use integrated limits.
energy_threshold_fraction (float, optional)
    Fraction of the stable energy-peak count used to derive ERANGE (default: 0.01).
plot_histograms (bool, optional)
    Plot histograms of the event data.
output_file (str, optional)
    Path to the output file for the derived limits.
output_path (str, optional)
    Path to the output directory for the derived limits and plots.
site (str, optional)
    Site for which to derive limits (e.g., North or South).

Example
-------

Derive limits for a single production with a list of array layouts:

.. code-block:: console

    simtools-production-derive-corsika-limits \\
        --trigger_histogram_file trigger_histograms.hdf5 \\
        --array_layout_name alpha beta \\
        --allowed_losses core_distance,1e-6,10 \
        --allowed_losses angular_distance,1e-6,10 \
        --energy_threshold_fraction 0.01 \
        --plot_histograms \\
        --output_file corsika_simulation_limits.ecsv

Derive limits for all arrays and productions in a trigger-histogram file:

.. code-block:: console

    simtools-production-derive-corsika-limits \\
        --trigger_histogram_file trigger_histograms.hdf5 \\
        --allowed_losses all,1e-6,10 \
        --energy_threshold_fraction 0.01 \
        --plot_histograms \\
        --output_file corsika_simulation_limits.ecsv

Results are merged into a single output ECSV with a ``production_index`` column, and plot files
are organized into per-production subdirectories when several productions are stored in the
histogram file.
"""

from simtools.application_control import build_application
from simtools.configuration.commandline_argument_helpers import efficiency_interval
from simtools.production_configuration.derive_corsika_limits import (
    generate_corsika_limits_grid,
)


def _add_arguments(parser):
    """Register application-specific command line arguments."""
    parser.add_argument(
        "--trigger_histogram_file",
        help=("Precomputed trigger-histogram HDF5 file from simtools-write-trigger-histograms. "),
        type=str,
        required=True,
    )
    parser.add_argument(
        "--array_layout_name",
        help=(
            "Optional array layout name(s) to select from a precomputed trigger-histogram "
            "file. If omitted, derive limits for all layouts available in the file."
        ),
        nargs="+",
        type=str,
        required=False,
        default=None,
    )
    parser.add_argument(
        "--allowed_losses",
        type=str,
        required=True,
        nargs="+",
        action="extend",
        metavar="AXIS,FRACTION,MIN_EVENTS",
        help=(
            "Per-axis allowed losses as axis,fraction,min_events. Repeat this argument "
            "for each axis using canonical names core_distance, angular_distance, "
            "or use all to set both. "
            "Example: --allowed_losses core_distance,1e-6,10"
        ),
    )
    parser.add_argument(
        "--energy_threshold_fraction",
        help="Fraction of the stable energy-peak count used to derive ERANGE ",
        type=efficiency_interval,
        required=False,
        default=0.01,
    )
    parser.add_argument(
        "--plot_histograms",
        help="Plot histograms of the event data.",
        action="store_true",
        default=False,
    )
    parser.add_argument(
        "--differential_loss_bins_per_decade",
        help=(
            "Number of differential energy bins per decade for per-bin limit computation. "
            "Set to 0 (default) to use integrated limits."
        ),
        type=int,
        required=False,
        default=0,
    )


def main():
    """See CLI description."""
    build_application(initialization_kwargs={"db_config": False, "output": True})
    generate_corsika_limits_grid()


if __name__ == "__main__":
    main()
