#!/usr/bin/python3

r"""
Derive CORSIKA configuration limits for energy, core distance, and viewcone radius.

This tool derives configuration limits from reduced event data generated by broad-range
simulations. It supports the derivation of the following CORSIKA configuration parameters:

- **ERANGE**: lower energy limit
- **CSCAT**: upper core distance
- **VIEWCONE**: viewcone radius

Broad-range simulations in this context are simulation sets generated with wide ranges
for these parameters.

How limits are derived
----------------------
Lower energy limit (**ERANGE**)
    Derived from the 1D triggered-energy histogram using a peak-relative threshold:

    1. Find the absolute maximum bin in the triggered-energy histogram.
    2. Compute a stable peak by averaging the maximum bin and available immediate neighbors.
    3. Define a threshold as fraction of this stable peak (``--energy_threshold_fraction``).
    4. Walk toward lower energies from the peak to the first bin below threshold.
    5. Use that bin's lower edge as the energy limit.

Upper core distance (**CSCAT**) and viewcone radius (**VIEWCONE**)
    Derived from per-axis allowed-loss settings (``--allowed_losses` axis,fraction,min_events``),
    either as integrated limits or per-energy-bin
    differential limits (depending on ``--differential_loss_bins_per_decade``).
    Differential limits are preferable, as they are more robust to variations with energy.

Results are provided as a table with the following columns:

+---------------------------+-----------+--------+----------------------------------------------+
| Field                     | Data Type | Units  | Description                                  |
+===========================+===========+========+==============================================+
| production_index          | int64     |        | Production index for multi-production runs.  |
+---------------------------+-----------+--------+----------------------------------------------+
| primary_particle          | string    |        | Particle type (e.g., gamma, proton).         |
+---------------------------+-----------+--------+----------------------------------------------+
| array_name                | string    |        | Array name (custom or as defined in          |
|                           |           |        | array_layouts).                              |
+---------------------------+-----------+--------+----------------------------------------------+
| zenith                    | float64   | deg    | Direction of array pointing zenith.          |
+---------------------------+-----------+--------+----------------------------------------------+
| azimuth                   | float64   | deg    | Direction of array pointing azimuth.         |
+---------------------------+-----------+--------+----------------------------------------------+
| nsb_level                 | float64   |        | Night sky background level.                  |
+---------------------------+-----------+--------+----------------------------------------------+
| lower_energy_limit        | float64   | TeV    | Derived lower energy limit (**ERANGE**).     |
+---------------------------+-----------+--------+----------------------------------------------+
| upper_radius_limit        | float64   | m      | Derived upper core distance                  |
|                           |           |        | (**CSCAT**).                                 |
+---------------------------+-----------+--------+----------------------------------------------+
| viewcone_radius           | float64   | deg    | Derived viewcone radius (**VIEWCONE**).      |
+---------------------------+-----------+--------+----------------------------------------------+
| br_energy_min             | float64   | TeV    | Energy min from broad-range simulations.     |
+---------------------------+-----------+--------+----------------------------------------------+
| br_energy_max             | float64   | TeV    | Energy max from broad-range simulations.     |
+---------------------------+-----------+--------+----------------------------------------------+
| br_core_scatter_max       | float64   | m      | Core scatter max from broad-range            |
|                           |           |        | simulations.                                 |
+---------------------------+-----------+--------+----------------------------------------------+
| br_viewcone_max           | float64   | deg    | Viewcone max from broad-range simulations.   |
+---------------------------+-----------+--------+----------------------------------------------+

The input event data files are generated using the application simtools-generate-simtel-event-data
and are required for each point in the observational parameter space (e.g., array pointing
directions, level of night sky background, etc.).

Distributions of triggered events (e.g., core distance vs energy) can by plotted to verify the
derived limits using the ``--plot_histograms`` option. Plots are organized into per-production
subdirectories derived from the input pattern names (for example ``production_production_a/``).

Command line arguments
----------------------
event_data_file (str or list of str, required)
    Path or glob pattern for reduced event data files. Can be a single pattern or
    multiple patterns (one per ``--event_data_file`` argument) to enable parallel
    multi-production processing.
array_layout_name (str, required)
    Name of the array layout (as defined in array_layouts) for which to derive limits.
    Single-telescope layouts can be defined using the telescope ID as array name
    (e.g. "MSTN-05").
allowed_losses (str, required, repeatable)
    Per-axis allowed-loss tuple in the form
    ``axis,fraction,min_events``.
    Use once per axis (core_distance, angular_distance), or use ``all``
    to set both axes and optionally override selected axes.
    Core distance and angular distance limits use these settings directly.
differential_loss_bins_per_decade (int, optional)
    Number of differential energy bins per decade for per-bin limit computation.
    Set to 0 (default) to use integrated limits.
energy_threshold_fraction (float, optional)
    Fraction of the stable energy-peak count used to derive ERANGE (default: 0.01).
model_version (str, required)
    Simulation model version (e.g., "7.0.0") to retrieve the corresponding
    array layout.
n_workers (int, optional)
    Number of worker processes to use for execution. Default is 1.
plot_histograms (bool, optional)
    Plot histograms of the event data.
output_file (str, optional)
    Path to the output file for the derived limits.
output_path (str, optional)
    Path to the output directory for the derived limits and plots.
site (str, optional)
    Site for which to derive limits (e.g., North or South).

Example
-------

Derive limits for a single production with a list of array layouts:

.. code-block:: console

    simtools-production-derive-corsika-limits \\
        --event_data_file event_dat_file.hdf5 \\
        --array_layout_name alpha,beta \\
        --allowed_losses core_distance,1e-6,10 \
        --allowed_losses angular_distance,1e-6,10 \
        --energy_threshold_fraction 0.01 \
        --plot_histograms \\
        --output_file corsika_simulation_limits.ecsv

Derive limits for multiple independent productions in parallel:

.. code-block:: console

    simtools-production-derive-corsika-limits \\
        --event_data_file pattern_1_*.hdf5 \\
        --event_data_file pattern_2_*.hdf5 \\
        --array_layout_name alpha \\
        --allowed_losses all,1e-6,10 \
        --energy_threshold_fraction 0.01 \
        --plot_histograms \\
        --n_workers 4 \\
        --output_file corsika_simulation_limits.ecsv

When multiple ``--event_data_file`` patterns are provided, results are merged into a single output
ECSV with a ``production_index`` column, and plot files are organized into per-production
subdirectories derived from the input pattern names (for example ``production_production_a/``).
"""

from simtools.application_control import build_application
from simtools.production_configuration.derive_corsika_limits import (
    generate_corsika_limits_grid,
)


def _add_arguments(parser):
    """Register application-specific command line arguments."""
    parser.initialize_application_arguments(["telescope_ids"])
    # Override event_data_file to allow multiple patterns for multi-production support
    parser.add_argument(
        "--event_data_file",
        help=(
            "Event data file or glob pattern (one or more patterns for "
            "multi-production processing)."
        ),
        nargs="+",
        action="extend",
        required=True,
    )
    parser.add_argument(
        "--allowed_losses",
        type=str,
        required=True,
        nargs="+",
        action="extend",
        metavar="AXIS,FRACTION,MIN_EVENTS",
        help=(
            "Per-axis allowed losses as axis,fraction,min_events. Repeat this argument "
            "for each axis using canonical names core_distance, angular_distance, "
            "or use all to set both. "
            "Example: --allowed_losses core_distance,1e-6,10"
        ),
    )
    parser.add_argument(
        "--energy_threshold_fraction",
        help="Fraction of the stable energy-peak count used to derive ERANGE ",
        type=parser.efficiency_interval,
        required=False,
        default=0.01,
    )
    parser.add_argument(
        "--plot_histograms",
        help="Plot histograms of the event data.",
        action="store_true",
        default=False,
    )
    parser.add_argument(
        "--n_workers",
        help=(
            "Number of worker processes to use for execution "
            "(default: 1; set to 0 for auto-detection of available cores)."
        ),
        type=int,
        required=False,
        default=1,
    )
    parser.add_argument(
        "--differential_loss_bins_per_decade",
        help=(
            "Number of differential energy bins per decade for per-bin limit computation. "
            "Set to 0 (default) to use integrated limits."
        ),
        type=int,
        required=False,
        default=0,
    )


def main():
    """See CLI description."""
    app_context = build_application(
        initialization_kwargs={
            "db_config": True,
            "output": True,
            "simulation_model": [
                "site",
                "model_version",
                "layout",
            ],
        },
    )

    generate_corsika_limits_grid(app_context.args)


if __name__ == "__main__":
    main()
