#!/usr/bin/python3

"""
Run several simtools applications using a configuration file.

Allows to run several simtools applications with a single configuration file, which includes
both the name of the simtools application and the configuration for the application.

This application is used for model parameter setting workflows.
Strong assumptions are applied on the directory structure for input and output files of
applications, for details see the CTAO Simulation Model Parameter Setting
`repository <https://gitlab.cta-observatory.org/cta-science/simulations/simulation-model/\
simulation-model-parameter-setting>`_.

.. tip::
   Browse the CTAO Simulation Model Parameter Setting
   `repository <https://gitlab.cta-observatory.org/cta-science/simulations/simulation-model/\
simulation-model-parameter-setting>`_
   for a list of examples and templates for configuration files.

For simplified configuration, a placeholder called ``__SETTING_WORKFLOW__`` can be used in the
configuration file. This placeholder will be replaced with the directory below ``input``
(example: configuration file is in
``input/LSTN-design/num_gains/019d776b-e24c-741d-bc05-e3f6f7ec77c7/config.yml``,
then the placeholder will be replaced with
``LSTN-design/num_gains/019d776b-e24c-741d-bc05-e3f6f7ec77c7``).
This will also be the directory for any output generated by the application.

Run time environments can be defined in the configuration file using the ``runtime_environment``
block, or in a standalone file passed with ``--runtime_environment_file``. The following example
shows how to define a runtime environment:

.. code-block:: yaml

    runtime_environment:
        image: ghcr.io/gammasim/simtools-prod-sim-telarray-240927-corsika-77550-bernlohr-1.68-\
prod6-baseline-qgs2-no_opt:20250716-122341
        network: simtools-mongo-network
        environment_file: ./.env
        container_engine: podman
        options:
        - '--arch amd64'

If the ``ignore_runtime_environment`` flag is set, the application will run in the current
environment, ignoring any definitions in the configuration file.

If the ``overwrite_collection_files`` flag is set, files collected in the optional
``collection`` block of the workflow configuration are allowed to overwrite existing
destination files with the same basename.

The database configuration and setting of other environment variables is done as
described in :ref:`environment-variables`.

Example
-------

Run the application with the configuration file ``config_file_name``:

.. code-block:: console

    simtools-run-application --config_file config_file_name

Run the application with the configuration file ``config_file_name``, but skipping all steps except
step 2 and 3 (useful for debugging):

.. code-block:: console

    simtools-run-application --config_file config_file_name --steps 2 3

"""

from simtools.application.definition import ApplicationDefinition
from simtools.configuration import arguments as cli
from simtools.runners.simtools_runner import run_applications

_ARGUMENTS = (
    cli.ArgumentDefinition(
        "config_file", help="Application configuration.", type=str, required=True, default=None
    ),
    cli.ArgumentDefinition(
        "steps",
        type=int,
        nargs="+",
        help="List of steps to be execution (e.g., '--steps 7 8 9'; do not specify to run all).",
    ),
)


APPLICATION = ApplicationDefinition.for_module(
    __name__,
    arguments=(*_ARGUMENTS,),
    database=True,
    setup_io_handler=False,
    resolve_sim_software_executables=False,
    usage="simtools-run-application --config_file config_file_name",
)


def main():
    """Run several simtools applications using a configuration file."""
    app_context = APPLICATION.start()

    run_applications(app_context.args, run_time=app_context.run_time)


if __name__ == "__main__":
    main()
