#!/usr/bin/python3

r"""
    Validate the optical model parameters through ray tracing simulations of the whole telescope.

    A point-like light source is assumed. The output includes PSF (D80), \
    effective mirror area and effective focal length as a function of the off-axis angle. \

    The telescope zenith angle and the source distance can be set by command line arguments.

    Examples of the plots generated by this application are shown below. On the top, the D80 \
    vs off-axis is shown in cm (left) and deg (right). On the bottom, the effective mirror \
    area (left) and the effective focal length (right) vs off-axis angle are shown.

    .. _validate_optics_plot:
    .. image::  images/validate_optics_North-LST-1_d80_cm.png
      :width: 49 %
    .. image::  images/validate_optics_North-LST-1_d80_deg.png
      :width: 49 %

    .. image::  images/validate_optics_North-LST-1_eff_area.png
      :width: 49 %
    .. image::  images/validate_optics_North-LST-1_eff_flen.png
      :width: 49 %


    Command line arguments
    ----------------------
    site (str, required)
        North or South.
    telescope (str, required)
        Telescope model name (e.g. LST-1, SST-D, ...).
    model_version (str, optional)
        Model version.
    source_distance (float or quantity, optional)
        Source distance in km.
    zenith_angle (float or quantity, optional)
        Zenith angle in deg.
    max_offset (float or quantity, optional)
        Maximum offset angle in deg.
    offset_step (float or quantity, optional)
        Offset angle step size.
    plot_images (activation mode, optional)
        Produce a multiple pages pdf file with the image plots.
    test (activation mode, optional)
        If activated, application will be faster by simulating fewer photons.

    Example
    -------
    LST-1 5.0.0

    .. code-block:: console

        simtools-validate-optics --site North --telescope LST-1 --max_offset 1.0 \\
        --zenith_angle 20 --source_distance 10 --test

    The output is saved in simtools-output/validate_optics

    Expected final print-out message:

    .. code-block:: console

        INFO::ray_tracing(l434)::plot::Plotting eff_area vs off-axis angle
        INFO::ray_tracing(l434)::plot::Plotting eff_flen vs off-axis angle

"""

from simtools.application_control import build_application
from simtools.ray_tracing.optics_validation import validate_optics


def _add_arguments(parser):
    """Register application-specific command line arguments."""
    parser.initialize_application_arguments(
        ["source_distance", "zenith_angle", "max_offset", "offset_step"]
    )
    parser.add_argument(
        "--offset_file",
        help="Path to ECSV file with x, y offset columns (in degrees). "
        "If provided, overrides max_offset and offset_step.",
        type=str,
        default=None,
    )
    parser.add_argument(
        "--offset_directions",
        help="Cardinal directions for offset generation (comma-separated): N,S,E,W. "
        "Only used with max_offset. Default: all four directions.",
        type=str,
        default="N,S,E,W",
    )
    parser.add_argument(
        "--plot_images",
        help="Produce a multiple pages pdf file with the image plots.",
        action="store_true",
    )


def main():
    """See CLI description."""
    app_context = build_application(
        initialization_kwargs={
            "db_config": True,
            "simulation_model": ["telescope", "model_version"],
        },
    )
    validate_optics(app_context)


if __name__ == "__main__":
    main()
