---
name: CI-schema-validation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/CI-schema-validation.yml'
      - 'src/simtools/schemas/model_parameters/**'
      - 'src/simtools/schemas/model_parameter_and_data_schema.metaschema.yml'
      - 'src/simtools/schemas/application_workflow.metaschema.yml'
      - 'src/simtools/data_model/schema.py'
      - 'src/simtools/data_model/schema_loader.py'
      - 'src/simtools/applications/validate_file_using_schema.py'
      - 'tests/integration_tests/config/**'

permissions: {}

jobs:

  schema-validation:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -leo pipefail {0}

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7
        with:
          python-version: "3.14"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Installation
        run: |
          pip install -e .

      - name: Check for files without the suffix *.schema.yml
        run: |
          shopt -s nullglob globstar
          files=(src/simtools/schemas/model_parameters/**/*.yml)
          if (( ${#files[@]} == 0 )); then
            echo "No model parameter YAML files found"
            exit 1
          fi
          for file in "${files[@]}"; do
            if [[ $file != *.schema.yml ]]; then
              echo "File $file does not have the suffix *.schema.yml"
              exit 1
            fi
          done

      - name: Model parameter schema validation
        run: |
          simtools-validate-file-using-schema \
            --file_directory src/simtools/schemas/model_parameters \
            --file_name '*.yml' \
            --schema_file model_parameter_and_data_schema.metaschema.yml \
            --data_type schema \
            --ignore_software_version \
            --log_level INFO

      - name: Integration test config file validation
        run: |
          simtools-validate-file-using-schema \
            --file_directory tests/integration_tests/config \
            --file_name '*.yml' \
            --schema_file application_workflow.metaschema.yml \
            --data_type schema \
            --log_level INFO
