---
# Derived from https://github.com/cta-observatory/project-template-python-pure/blob/main/.github/workflows/pypi.yml
name: Deploy to PyPi

on:
  workflow_dispatch:
  release:
    types: [published]

permissions: {}

jobs:
  deploy:
    if: >-
      (github.event_name == 'workflow_dispatch' && !contains(github.ref_name, '-rc')) ||
      (github.event_name == 'release' && !contains(github.event.release.tag_name, '-rc'))
    runs-on: ubuntu-latest
    environment: pypi-release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      # make sure we have version info
      - run: git fetch --tags

      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  # v7
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: |
          python --version
          pip install -U build
          python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@dc37677b2e1c63e2034f94d8a5b11f265b73ba33  # release/v1
